Feature/core 9317 foreign object width
geoblink/design-system pull request #101
Opened 2021-12-01 13:19 UTC by dletran

2021-12-01 13:37 UTC, fofi requested changes

2021-12-01 13:37 UTC, fofi commented on CHANGELOG.md
> +- `GeoChart`: Fix negative width for axis ticks
Lets try to follow always the same comment structure.
I think the more accurate is the one with a section for Fix, Changed, New

2021-12-01 13:37 UTC, fofi commented on src/elements/GeoChart/GeoChartAxis/GeoChartAxis.js
> +      foreignObjectElem.attr('width', _.max([width, 0]))
We should probably add a test for this case if possible

2021-12-02 08:58 UTC, fofi approved these changes

2021-12-02 09:13 UTC, Navas23 approved these changes

2021-12-02 13:24 UTC, merged