Feature/core 8781 show value label in bar chart
geoblink/design-system pull request #107
Opened 2022-05-31 10:09 UTC by irmakyz

2022-06-02 07:59 UTC, irmakyz commented on src/elements/GeoChart/GeoChartConfigs/GeoChartConfigAdapter.mixin.js
> +              _.first(this.config.labelGroups[labelIndex].data[index].labels).text = `${parseFloat(data.value) / 10}%`
so, i shouldn't send the values here but it will be done while there is a bar creation in the app ?

2022-06-02 07:59 UTC, irmakyz commented on src/elements/GeoChart/GeoChartConfigs/GeoChartConfigAdapter.mixin.js
> +              _.first(this.config.labelGroups[labelIndex].data[index].labels).text = `${parseFloat(data.value) / 10}%`
should i handle value changes in anywhere

2022-06-02 08:01 UTC, irmakyz commented on src/elements/GeoChart/GeoChartLabels/GeoChartLabels.js
> +    verticalAxisTranslation = verticalAxisTranslationToTopPosition - 40
it is for having margins in the vertical labels, but i can set them as margin, but in this case they have to handle it everytime

2022-06-02 08:03 UTC, irmakyz commented on src/elements/GeoChart/GeoChartLabels/GeoChartLabels.js
> +    const yTranslation = (tallestGroupHeight - heightWithPaddingAndMargin)
you are right, actually i forgot it, deleting now

2022-06-02 08:04 UTC, irmakyz commented on src/elements/GeoChart/GeoChartConfigs/GeoChartConfig.js
> +    hasLabelValues: {
yes isPositioningLabelsInBars makes more sense

2022-06-02 15:17 UTC, dletran reviewed
Nice job! just a few small comments

2022-06-02 15:17 UTC, dletran commented on src/elements/GeoChart/GeoChartConfigs/GeoChartConfig.js
> +    isVerticalLabel: {
I think instead of a new flag we could use the `mainDimension` prop that tells you if the chart is going to be horizontal or vertical, wdyt?

2022-06-02 15:17 UTC, dletran commented on src/elements/GeoChart/GeoChartLabels/GeoChartLabels.js
> +    verticalAxisTranslation = verticalAxisTranslationToTopPosition - 40
can we store the 40 in a constant so it's more clear what it is for? something like:
`const marginFromBarToLabel = 40`

2022-06-02 15:17 UTC, dletran commented on src/elements/GeoChart/GeoChartConfigs/GeoChartConfigAdapter.mixin.js
> +              _.first(this.config.labelGroups[labelIndex].data[index].labels).text = `${parseFloat(data.value) / 10}%`
exactly, while creating chartConfigs we can send a custom function to transform the values so we can leave this generic without any transformation

2022-06-02 15:17 UTC, dletran commented on src/elements/GeoChart/GeoChart.05.labels.examples.md
> +      if (parseFloat(data) < 1000) {
this is just for the demo examples right? we can keep it simple next time but it's fine 👌

2022-06-02 15:17 UTC, dletran commented on src/elements/GeoChart/GeoChartConfigs/GeoChartConfigAdapter.mixin.js
> -
really small thing but in my opinion these blank lines helped a bit with readability specially with big blocks of code, wdyt?

2022-06-02 15:17 UTC, dletran commented on src/elements/GeoChart/GeoChartLabels/GeoChartLabels.d.ts
> +    cssClasses?: (defaultClasses: string[], item: object, index: number) => string[],
you have a trailing comma here, I think lint will complain you can check the lint issues by launching `yarn lint`

2022-06-02 15:17 UTC, dletran commented on src/elements/GeoChart/GeoChartLabels/GeoChartLabels.js
> +    } = (positioningAttributes).shift()
why do we need this parentheses?

2022-06-02 15:20 UTC, dletran commented on src/elements/GeoChart/GeoChartLabels/GeoChartLabels.js
> +      verticalAxisTranslation = verticalAxisTranslationToTopPosition - 40
maybe we should let the user decide on this margin and have a default value for it as part of the labels config, wdyt? and it could work too for horizontal

2022-06-06 10:32 UTC, irmakyz commented on src/elements/GeoChart/GeoChartLabels/GeoChartLabels.js
> +      verticalAxisTranslation = verticalAxisTranslationToTopPosition - 40
well, yes sure!

2022-06-06 10:33 UTC, irmakyz commented on src/elements/GeoChart/GeoChartLabels/GeoChartLabels.js
> +    } = (positioningAttributes).shift()
i forgot it from previous modifications i guess

2022-06-06 10:33 UTC, irmakyz commented on src/elements/GeoChart/GeoChartConfigs/GeoChartConfigAdapter.mixin.js
> -
yes, exactly, i am adding them

2022-06-06 10:34 UTC, irmakyz commented on src/elements/GeoChart/GeoChart.05.labels.examples.md
> +      if (parseFloat(data) < 1000) {
yes, they are... true i have to make them simple :D

2022-06-06 10:37 UTC, irmakyz commented on src/elements/GeoChart/GeoChartConfigs/GeoChartConfig.js
> +    isVerticalLabel: {
well actually, i will try again

2022-06-07 08:26 UTC, dletran reviewed
Just some last small comments, it's looking better now 👏

2022-06-07 08:26 UTC, dletran commented on src/elements/GeoChart/GeoChartLabels/GeoChartLabels.js
> +      horizontalAxisTranslation = horizontalAxisTranslationToTopPosition - (horizontalAxisTranslationToTopPosition + width >= chartWidth
maybe we could separate this into two statements so it's more readable, wdyt? one to calculate the offset  and the other with the assignment to horizontalAxisTranslation

2022-06-07 08:27 UTC, irmakyz commented on src/elements/GeoChart/GeoChart.05.labels.examples.md
> +        /**this.linearAxisConfigKeyForValues.push(_.random(
oh, i am deleting it :D

2022-06-07 08:28 UTC, irmakyz commented on src/elements/GeoChart/GeoChartConfigs/GeoChartConfigAdapter.mixin.js
> +              _.first(data.labels).margin = _.first(data.labels).margin
i thought that, the labels shouldn't have more then one, since it is the labels of bar groups which are shown in the top of them

2022-06-07 08:28 UTC, irmakyz commented on src/elements/GeoChart/GeoChartConfigs/GeoChartConfigAdapter.mixin.js
> +              _.first(data.labels).margin = _.first(data.labels).margin
thank you for the tip!

2022-06-07 08:28 UTC, irmakyz commented on src/elements/GeoChart/GeoChartLabels/GeoChartLabels.js
> +      horizontalAxisTranslation = horizontalAxisTranslationToTopPosition - (horizontalAxisTranslationToTopPosition + width >= chartWidth
yes sure!

2022-06-07 08:40 UTC, dletran commented on src/elements/GeoChart/GeoChartConfigs/GeoChartConfigAdapter.mixin.js
> +              _.first(data.labels).margin = _.first(data.labels).margin
I think there are some cases where we could have more than 1 group of labels, according to our own docs on labels:

> Sometimes you might want to add custom labels to the chart, anchored to the items already displayed in it, **even multiple labels for each item** in the chart

so maybe we should apply it to all of them and check it works for several groups too

2022-06-07 08:43 UTC, irmakyz commented on src/elements/GeoChart/GeoChartConfigs/GeoChartConfigAdapter.mixin.js
> +              _.first(data.labels).margin = _.first(data.labels).margin
oh okay, soo but they shouldn't be with the margins, they should be inside of the bars, right ?

2022-06-07 08:53 UTC, dletran commented on src/elements/GeoChart/GeoChartConfigs/GeoChartConfigAdapter.mixin.js
> +              _.first(data.labels).margin = _.first(data.labels).margin
why can't we do the same for all labels?

2022-06-07 08:58 UTC, dletran commented on src/elements/GeoChart/GeoChartConfigs/GeoChartConfigAdapter.mixin.js
> +              _.first(data.labels).margin = _.first(data.labels).margin
ok so let's check if it makes sense and if not we can just add a comment on the docs for this new property to warn that it's only for the first group of labels

2022-06-07 10:18 UTC, dletran commented on src/elements/GeoChart/GeoChartConfigs/GeoChartConfigAdapter.mixin.js
> +              (data.labels).forEach((label) => {
let's use Lodash here `_.forEach(data.labels, label => {...})`

2022-06-07 11:20 UTC, dletran approved these changes

2022-06-07 13:11 UTC, Navas23 reviewed
Looks good! Don't forget to add your changes to the changelog.md file

2022-06-07 13:11 UTC, Navas23 commented on src/elements/GeoChart/GeoChartLabels/GeoChartLabels.d.ts
> +    labels: SingleLabelConfig[],
Care with this trailing comma

2022-06-07 13:11 UTC, Navas23 commented on src/elements/GeoChart/GeoChartLabels/GeoChartLabels.d.ts
> +    cssClasses?: (defaultClasses: string[], item: object, index: number) => string[],
Don't forget about this

2022-06-07 14:17 UTC, fofi requested changes
Do not forget to update the changelog and the versioning!

2022-06-07 14:17 UTC, fofi commented on src/elements/GeoChart/GeoChart.05.labels.examples.md
> +### Optional properties
It will be required to have or `idVerticalAxis` or `idHorizontalAxis`

And with thar poerty we know if it will be vertical or not, right?

It is possible to have both at the same time?

2022-06-07 14:17 UTC, fofi commented on src/elements/GeoChart/GeoChart.05.labels.examples.md
> +          [this.linearAxisConfig.keyForValues]:_.random(
Care with this space

2022-06-07 14:17 UTC, fofi commented on src/elements/GeoChart/GeoChart.05.labels.examples.md
> +add the **isPositioningLabelsInBars** boolean to the bar chart config.
What does exactly `isPositioningLabelsInBars` menas? I mean, whats the difference with the other label?

2022-06-07 14:17 UTC, fofi commented on src/elements/GeoChart/GeoChart.05.labels.examples.md
> +          idVerticalAxis: this.linearAxisConfig.id,
We need to set both here?

2022-06-07 14:17 UTC, fofi commented on src/elements/GeoChart/GeoChartLabels/GeoChartLabels.js
>    const verticalAxisTranslationToTopPosition = getItemValueAtAxis(verticalAxis, singleItem)
Why are we executing vertical code also in the case in which the axis is horizontal? 

I think this code is not super clear

In my head, if the axis is horizontal we need the axis position of the horizontal axis


Why before we were just using one axis and now we need both?

2022-06-07 14:17 UTC, fofi commented on src/elements/GeoChart/GeoChartConfigs/GeoChartConfigAdapter.mixin.js
> +          if (singleBarGroupConfig.mainDimension === 'vertical') {
We should always use constants instead of hardcoded literals

2022-06-07 14:17 UTC, fofi commented on src/elements/GeoChart/GeoChartConfigs/GeoChartConfigAdapter.mixin.js
> +                }
Why these margins?

2022-06-07 15:48 UTC, irmakyz commented on src/elements/GeoChart/GeoChart.05.labels.examples.md
> +add the **isPositioningLabelsInBars** boolean to the bar chart config.
This label is for the bar groups and they are at the end of each bar. Normally the labels are only horizontal and in the beginning of the bars, they are positioned in the same level

2022-06-07 15:49 UTC, irmakyz commented on src/elements/GeoChart/GeoChart.05.labels.examples.md
> +### Optional properties
yes, for the horizontal labels, we need both so it makes a confusion. that's why i am sending the mainDimension in the adapter

2022-06-07 15:49 UTC, irmakyz commented on src/elements/GeoChart/GeoChartConfigs/GeoChartConfigAdapter.mixin.js
> +          if (singleBarGroupConfig.mainDimension === 'vertical') {
sure, i am fixing

2022-06-07 15:53 UTC, irmakyz commented on src/elements/GeoChart/GeoChart.05.labels.examples.md
> +          idVerticalAxis: this.linearAxisConfig.id,
yes for horizontal ones, we have to otherwise it have a conflict since we have to consider the values of the bar groups

2022-06-08 11:28 UTC, fofi requested changes

2022-06-08 11:28 UTC, fofi commented on src/elements/GeoChart/GeoChart.05.labels.examples.md
> +### Optional properties
Oki thanks

2022-06-08 11:28 UTC, fofi commented on src/elements/GeoChart/GeoChartConfigs/GeoChartConfigAdapter.mixin.js
> +          } else {
We want to execute this if the `mainDimension` is `horizontal` or always if the main dimension is not vertical?

2022-06-08 11:28 UTC, fofi commented on src/elements/GeoChart/GeoChartLabels/GeoChartLabels.d.ts
> +    data: SingleLabelLineConfig[],
Remove comma

2022-06-08 11:28 UTC, fofi commented on src/elements/GeoChart/GeoChartLabels/GeoChartLabels.js
> +    if (singleGroupOptions.mainDimension === 'vertical') {
Same here, use constants

2022-06-08 11:28 UTC, fofi commented on src/elements/GeoChart/GeoChartLabels/GeoChartLabels.js
> +        : verticalAxisTranslationToTopPosition - _.first(singleItem.labels).margin.top
It could happen that `verticalAxisTranslationToTopPosition - _.first(singleItem.labels).margin.top` is negative? Is that fine?

2022-06-08 15:23 UTC, irmakyz commented on src/elements/GeoChart/GeoChartConfigs/GeoChartConfigAdapter.mixin.js
> +          } else {
if the main dimension is horizontal, should i say it as === horizontal

2022-06-08 15:24 UTC, irmakyz commented on src/elements/GeoChart/GeoChartLabels/GeoChartLabels.js
> +        : verticalAxisTranslationToTopPosition - _.first(singleItem.labels).margin.top
i guess so, but i can try to test it just in case

2022-06-08 15:30 UTC, irmakyz commented on src/elements/GeoChart/GeoChartLabels/GeoChartLabels.js
>    const verticalAxisTranslationToTopPosition = getItemValueAtAxis(verticalAxis, singleItem)
before, the labels were only shown in the left side of the grap, no relation with the values. now it has to check values so we need both axes. for vertical code, it has been there already. the part i added is 

for vertical ones:
1. to check the vertical position of the labels (vertical axis)
2. to check the horizontal position of the labels since the bar groups might have different widths ( horizontal)

for horizontal labels:
1. to check vertical position
2. to check horizontal position for the values

2022-06-09 11:04 UTC, fofi commented on src/elements/GeoChart/GeoChartLabels/GeoChartLabels.js
>          : verticalAxisTranslationToTopPosition - _.first(singleItem.labels).margin.top
A simplification of this code could be something like

`
verticalAxisTranslation = Math.min( verticalAxisTranslationToTopPosition - _.first(singleItem.labels).margin.top, 0)
`

2022-06-09 11:15 UTC, fofi commented on src/elements/GeoChart/GeoChartConfigs/GeoChartConfigAdapter.mixin.js
> +          } else {
Then lets add the condition also, is better to always write what we want, because else will be executed also if undefined

2022-06-09 15:45 UTC, irmakyz commented on src/elements/GeoChart/GeoChartLabels/GeoChartLabels.js
>          : verticalAxisTranslationToTopPosition - _.first(singleItem.labels).margin.top
shouldn't be Math.max? since we want the topPosition to be positive

2022-06-09 16:24 UTC, fofi commented on src/elements/GeoChart/GeoChartLabels/GeoChartLabels.js
>          : verticalAxisTranslationToTopPosition - _.first(singleItem.labels).margin.top
So true yes

2022-06-09 16:42 UTC, fofi commented on src/elements/GeoChart/GeoChartConfigs/GeoChartConfigAdapter.mixin.js
> +          this.config.labelGroups[index].mainDimension = singleBarGroupConfig.mainDimension
Why we only have to do this if  `singleBarGroupConfig.mainDimension === DIMENSIONS.DIMENSIONS_2D.horizontal` ?

2022-06-09 16:42 UTC, fofi commented on src/elements/GeoChart/GeoChartConfigs/GeoChartConfigAdapter.mixin.js
> +          }
We can simplify this a bit by setting a `defaultMargin` value and then applying it on the iteration, instead of writing the same iteration code 2 times
 
```
const defaultMargin = singleBarGroupConfig.mainDimension === DIMENSIONS.DIMENSIONS_2D.vertical
  ? { top: 30, bottom: 0, left: 0, right: 0 }
  : singleBarGroupConfig.mainDimension === DIMENSIONS.DIMENSIONS_2D.horizontal
    ? { top: 0, bottom: 0, left: 10, right: 0 }
    : null
```

2022-06-10 06:30 UTC, irmakyz commented on src/elements/GeoChart/GeoChartConfigs/GeoChartConfigAdapter.mixin.js
> +          this.config.labelGroups[index].mainDimension = singleBarGroupConfig.mainDimension
if it is horizontal, it sets the margin between bar and labels horizontally

2022-06-10 06:30 UTC, irmakyz commented on src/elements/GeoChart/GeoChartConfigs/GeoChartConfigAdapter.mixin.js
> +          }
thanks!

2022-06-10 06:33 UTC, irmakyz commented on src/elements/GeoChart/GeoChartLabels/GeoChartLabels.js
> +      const horizontalOffset = horizontalAxisTranslationToTopPosition + width >= chartWidth
if it is wider than the width of the chart, it cannot be shown as a total so i wanted to set it at the end of the bar chart and if there is a padding right, i am adding it as well.

2022-06-10 10:41 UTC, fofi approved these changes
Do not forget to set the changelog and the beta version for the testing

2022-06-10 10:55 UTC, fofi commented on src/elements/GeoChart/GeoChartConfigs/GeoChartConfigAdapter.mixin.js
>            this.config.labelGroups[index].mainDimension = singleBarGroupConfig.mainDimension
With this last change, we are executing this line on every case, if `singleBarGroupConfig.mainDimension` is vertical or horizontal

Before it was not like that, is that a problem?

2022-06-10 11:07 UTC, irmakyz commented on src/elements/GeoChart/GeoChartConfigs/GeoChartConfigAdapter.mixin.js
>            this.config.labelGroups[index].mainDimension = singleBarGroupConfig.mainDimension
but i am checking the mainDimension while setting the defaultMargin, doesn't it give the same result

2022-06-10 11:12 UTC, fofi commented on src/elements/GeoChart/GeoChartConfigs/GeoChartConfigAdapter.mixin.js
>            this.config.labelGroups[index].mainDimension = singleBarGroupConfig.mainDimension
For the margin yes,  but now we are assigning this.config.labelGroups[index].mainDimension a different thing.

For me it makes sense to have always the same code, just asking because this is different from the previous code

2022-06-10 11:24 UTC, fofi commented on src/elements/GeoChart/GeoChartConfigs/GeoChartConfigAdapter.mixin.js
>            this.config.labelGroups[index].mainDimension = singleBarGroupConfig.mainDimension
Perfect

2022-06-10 11:28 UTC, fofi approved these changes

2022-06-20 08:25 UTC, fofi approved these changes

2022-06-21 09:00 UTC, Navas23 commented on src/elements/GeoChart/GeoChartLabels/GeoChartLabels.js
> +  // allSingleDataGroups
Do we want to remove this?

2022-06-21 09:07 UTC, irmakyz commented on src/elements/GeoChart/GeoChartConfigs/GeoChartConfigAdapter.mixin.js
> +          const isHorizontal = singleBarGroupConfig.mainDimension === DIMENSIONS.DIMENSIONS_2D.horizontal
i did it according to a previous comment, actually one is enough, i can change it

2022-06-21 09:26 UTC, Navas23 approved these changes

2022-08-10 09:52 UTC, Navas23 commented on src/elements/GeoChart/GeoChartConfigs/GeoChartConfigAdapter.mixin.js
> +          const isVertical = singleBarGroupConfig.mainDimension === DIMENSIONS.DIMENSIONS_2D.vertical
Do we need this if we have isHorizontal defined?

2022-08-10 09:52 UTC, Navas23 commented on src/elements/GeoChart/GeoChart.05.labels.examples.md
> -          isPositioningLabelsInBars:true,
Are you sure we have to remove all of this information?

2022-08-10 09:52 UTC, Navas23 commented on src/elements/GeoChart/GeoChartConfigs/GeoChartConfigAdapter.mixin.js
> +              if (label.cssClasses) { customClass = label.cssClasses('') }
What is this doing?

2022-08-10 09:52 UTC, Navas23 commented on src/elements/GeoChart/GeoChartLabels/GeoChartLabels.js
> +        ? chartHeight / nComparisons / 2 * _.parseInt(singleGroupOptions.id) + 2
Why this +2?

2022-08-17 08:09 UTC, irmakyz commented on src/elements/GeoChart/GeoChart.05.labels.examples.md
> -          isPositioningLabelsInBars:true,
yes yes i was trying something removed those parts

2022-08-17 08:10 UTC, irmakyz commented on src/elements/GeoChart/GeoChartConfigs/GeoChartConfigAdapter.mixin.js
> +              if (label.cssClasses) { customClass = label.cssClasses('') }
i am getting the current cssClasses to not remove them while changing font size

2022-08-17 08:11 UTC, irmakyz commented on src/elements/GeoChart/GeoChartLabels/GeoChartLabels.js
> +        ? chartHeight / nComparisons / 2 * _.parseInt(singleGroupOptions.id) + 2
maybe i can add it as a padding, it was just to position the labels

2022-08-22 14:48 UTC, irmakyz commented on src/elements/GeoChart/GeoChartConfigs/GeoChartConfigAdapter.mixin.js
> +          const isVertical = singleBarGroupConfig.mainDimension === DIMENSIONS.DIMENSIONS_2D.vertical
true, i can use !isHorizontal

2022-08-23 10:43 UTC, fofi commented on src/elements/GeoChart/GeoChart.05.labels.examples.md
> +
Missing `nComparisons`  and `mainDimension`, right?

2022-08-23 10:43 UTC, fofi commented on src/elements/GeoChart/GeoChartConfigs/GeoChartConfigAdapter.mixin.js
> +          const defaultPadding = isHorizontal ? { top: 0, bottom: 0, left: 30, right: 10 } : { top: 0, bottom: 0, left: 0, right: 0 }
Try to use the same structure always, will make the code more readable.
For example here, write the code the same ways as the previous lines

2022-08-23 10:43 UTC, fofi commented on src/elements/GeoChart/GeoChartConfigs/GeoChartConfigAdapter.mixin.js
> +              let customClass
Why not adding here by default the class `geo-chart-value-label--small` that you added on the app, but is defined here, maybe is better to define it here and use it here

2022-08-23 10:43 UTC, fofi commented on src/elements/GeoChart/GeoChartConfigs/GeoChartConfigAdapter.mixin.js
> +              let customClass
Actually, we are always applying the class `geo-chart-value-label--medium`, why we need the small one?

2022-08-23 10:43 UTC, fofi commented on src/elements/GeoChart/GeoChartConfigs/GeoChartConfigAdapter.mixin.js
> +                label.padding.bottom = 2
The indentation here is hard to read, as we are not using the same structure as above, also because the indentation for the if and for the code inside is the same

2022-08-23 10:43 UTC, fofi commented on src/elements/GeoChart/GeoChartConfigs/GeoChartConfigAdapter.mixin.js
> +              if (label.cssClasses && isHorizontal &&
Why are we only overwritting `cssClasses` if it already exist? why not assing it anyway? we don't want to apply it on each case independently if the original label has it defined?

2022-08-23 10:43 UTC, fofi commented on src/elements/GeoChart/GeoChartConfigs/GeoChartConfigAdapter.mixin.js
> +                singleBarGroupConfig.data.length >= 6) {
Why 6? its a hardcoded number?

2022-08-23 13:43 UTC, irmakyz commented on src/elements/GeoChart/GeoChartConfigs/GeoChartConfigAdapter.mixin.js
> +              let customClass
for some comparisons, we need very small font size as we talked with luis, so it is needed actually

2022-08-23 13:44 UTC, irmakyz commented on src/elements/GeoChart/GeoChartConfigs/GeoChartConfigAdapter.mixin.js
> +              let customClass
in default i send it with small label, and if it is needed i convert it to medium

2022-08-23 13:44 UTC, irmakyz commented on src/elements/GeoChart/GeoChart.05.labels.examples.md
> +
yes, adding rn

2022-08-23 13:48 UTC, irmakyz commented on src/elements/GeoChart/GeoChartConfigs/GeoChartConfigAdapter.mixin.js
> +              if (label.cssClasses && isHorizontal &&
it is because of the bar widths and numbers, sometimes there can be so many bars that the font sizes are overlapping because of their size

2022-08-23 13:49 UTC, irmakyz commented on src/elements/GeoChart/GeoChartConfigs/GeoChartConfigAdapter.mixin.js
> +                singleBarGroupConfig.data.length >= 6) {
i tried to find to detect bar width but after 6 it becomes bigger so i added hardcode :(

2022-08-23 13:52 UTC, irmakyz commented on src/elements/GeoChart/GeoChart.05.labels.examples.md
> +
the mainDimension is added in adapter from bargroups automatically.

2022-08-23 14:34 UTC, irmakyz commented on src/elements/GeoChart/GeoChartConfigs/GeoChartConfigAdapter.mixin.js
> +              let customClass
okito

2022-08-23 15:19 UTC, fofi approved these changes

2022-08-29 14:32 UTC, Navas23 commented on src/elements/GeoChart/GeoChart.05.labels.examples.md
> +          naturalNormalOffset: naturalOffset + (1 * naturalWidth) + (1 * naturalPadding)
Why do we need the 1 *

2022-08-29 14:32 UTC, Navas23 commented on src/elements/GeoChart/GeoChartConfigs/GeoChartConfigAdapter.mixin.js
> +              // if (data.value >= maxDomain - domainRatio) { textClass = 'geo-chart-axis-label-border' }
We should remove this, right?

2022-08-29 14:32 UTC, Navas23 commented on src/elements/GeoChart/GeoChartLabels/GeoChartLabels.js
> +        return _.uniq([...customClasses, singleLabelGroupsBaseClass, _.get(d, 'customClass', '')]).join(' ')
I think we don't need to get the custom class here

2022-08-29 14:32 UTC, Navas23 commented on src/elements/GeoChart/GeoChartLabels/GeoChartLabels.js
> -    .attr('fill', d => _.get(d, 'color', 'black'))
Aren't we using this anymore?

2022-08-29 14:32 UTC, Navas23 commented on src/elements/GeoChart/GeoChartLabels/GeoChartLabels.js
> +          ? chartWidth / nComparisons / 2 * _.parseInt(singleGroupOptions.id) + horizontalComparisonOffset
I think this number are so hardcoded, we could at least add a comment to explain why we use this "formula"

2022-08-29 14:32 UTC, Navas23 commented on src/styles/elements/GeoChart/_geo-chart.scss
> +  .geo-chart-axis-label-border {
With this class name, I expected this to modify borders or margin but it's modifying the fill color, could we think of a better name?

2022-08-29 14:56 UTC, irmakyz commented on src/elements/GeoChart/GeoChart.05.labels.examples.md
> +          naturalNormalOffset: naturalOffset + (1 * naturalWidth) + (1 * naturalPadding)
oh i have to delete it, was for trying, actually they are getting calculated automatically

2022-08-29 14:56 UTC, irmakyz commented on src/elements/GeoChart/GeoChartConfigs/GeoChartConfigAdapter.mixin.js
> +              // if (data.value >= maxDomain - domainRatio) { textClass = 'geo-chart-axis-label-border' }
yess

2022-08-29 14:56 UTC, irmakyz commented on src/elements/GeoChart/GeoChartLabels/GeoChartLabels.js
> +        return _.uniq([...customClasses, singleLabelGroupsBaseClass, _.get(d, 'customClass', '')]).join(' ')
oki

2022-08-29 14:57 UTC, irmakyz commented on src/elements/GeoChart/GeoChartLabels/GeoChartLabels.js
> -    .attr('fill', d => _.get(d, 'color', 'black'))
yeah we don't use, instead we use the classes

2022-08-29 14:57 UTC, irmakyz commented on src/styles/elements/GeoChart/_geo-chart.scss
> +  .geo-chart-axis-label-border {
yes oki

2022-09-09 13:15 UTC, merged