uncheck the empty folders and make them unclickable
geoblink/design-system pull request #138
Opened 2023-11-09 12:10 UTC by irmakyz

2023-11-10 10:14 UTC, fofi commented on src/elements/GeoTree/GeoTreeItem.vue
> +      @click="(isSingleItem || !isEmptyCategory)? handleClick($event):()=>{}"
Is better to modify only `handleClick`, right?

2023-11-10 10:15 UTC, fofi commented on src/elements/GeoTree/GeoTreeItem.vue
> +        if (!_.isNil(category[this.keyForSubcategory]) && !_.size(category[this.keyForSubcategory])) return
This should return a boolean, right?

2023-11-10 10:15 UTC, fofi commented on CHANGELOG.md
> +New:
I think this is more a Fix

2023-11-13 09:19 UTC, Navas23 commented on src/elements/GeoTree/GeoTreeItem.vue
> +
I think in the DS we don't have empty lines in the component. We can decide if we wan't to add them from now on or not

2023-11-13 09:38 UTC, dletran commented on src/elements/GeoTree/GeoTreeItem.vue
> +
I'd say let's do it, IMO it helps readability as in the app

2023-11-13 12:24 UTC, irmakyz commented on src/elements/GeoTree/GeoTreeItem.vue
> +      @click="(isSingleItem || !isEmptyCategory)? handleClick($event):()=>{}"
- [ ] modify handleClick itself

2023-11-13 13:03 UTC, irmakyz commented on src/elements/GeoTree/GeoTreeItem.vue
> +        if (!_.isNil(category[this.keyForSubcategory]) && !_.size(category[this.keyForSubcategory])) return
yess, hmm my fault i should do it different

2023-11-13 13:04 UTC, irmakyz commented on src/elements/GeoTree/GeoTreeItem.vue
> +        if (!_.isNil(category[this.keyForSubcategory]) && !_.size(category[this.keyForSubcategory])) return
- [ ] fix allAreChildrenSelected

2023-11-13 13:05 UTC, irmakyz commented on CHANGELOG.md
> +New:
for the fixes don't we use patch ?

2023-11-13 13:06 UTC, irmakyz commented on src/elements/GeoTree/GeoTreeItem.vue
> +
i agree w david

2023-11-13 13:37 UTC, Navas23 commented on CHANGELOG.md
> +New:
He means the copy, to put Fix instead of New

2023-11-13 15:18 UTC, irmakyz commented on CHANGELOG.md
> +New:
- [ ] change copy of chagelog

2023-11-13 15:38 UTC, Navas23 commented on src/elements/GeoTree/GeoTreeItem.vue
> +    isEmptyCategory () {
We could pass a category to this method and reuse it in `isChecked`

2023-11-13 15:44 UTC, irmakyz commented on src/elements/GeoTree/GeoTreeItem.vue
> +    isEmptyCategory () {
hmmm right, better idea! 

- [ ] pass category to isEmptyCategory and reuse

2023-11-13 15:59 UTC, Navas23 approved these changes

2023-11-13 16:05 UTC, fofi requested changes

2023-11-13 16:05 UTC, fofi commented on CHANGELOG.md
> +Fixed:
We use "Fix", lets keep the same naming

2023-11-13 16:05 UTC, fofi commented on src/elements/GeoTree/GeoTreeItem.vue
> +      if (!this.isSingleItem && this.isEmptyCategory(this.category)) return
Why do we allow empty category if single item?

2023-11-14 17:13 UTC, fofi commented on src/elements/GeoTree/GeoTreeItem.vue
> +      if (!this.isSingleItem && this.isEmptyCategory(this.category)) return
Then, why not add the return inside the else condition?

2023-11-15 09:11 UTC, irmakyz commented on src/elements/GeoTree/GeoTreeItem.vue
> +      if (!this.isSingleItem && this.isEmptyCategory(this.category)) return
hmmm yes better i am changing it

- [ ] check condition in else

2023-11-15 09:24 UTC, fofi approved these changes

2023-11-15 09:51 UTC, dletran approved these changes

2023-11-15 14:09 UTC, merged