add second level load more button
geoblink/design-system pull request #139
Opened 2023-12-05 16:28 UTC by irmakyz

2023-12-05 16:46 UTC, Navas23 requested changes
With your solution we are only applying it to 1 sublevel

2023-12-05 16:46 UTC, Navas23 commented on src/elements/GeoTree/GeoTreeItem.vue
> +      return this.pageSize * this.visiblePages < this.category[this.keyForSubcategory].length
Let's use lodash to get the size

2023-12-05 16:56 UTC, Navas23 reviewed
Don't we need to pass the slot to the following geo-tree-item?

2023-12-05 16:56 UTC, Navas23 commented on package.json
> +  "version": "35.5.0-beta.5",
Why do we need 5 betas to test this? should be straightforward to test it in local

2023-12-05 16:58 UTC, irmakyz commented on package.json
> +  "version": "35.5.0-beta.5",
first 2 betas were used before, so i started from 2, i fixed the sub level issue and then saw your comment so i published another one, that's why it jumped from 3 to 5

2023-12-11 07:46 UTC, dletran commented on src/elements/GeoTree/GeoTreeItem.vue
> +          <slot name="moreItemResultsTextContent" />
I feel like we're mixing names in several places, I think we should either stick with `results` or `items` so we either have `moreResultsTextContent` or `moreItemsTextContent`

So if the flag is going to be `hasMoreResultsToLoad`, I'd say to use results also, wdyt?

2023-12-11 09:09 UTC, Navas23 commented
> With your solution we are only applying it to 1 sublevel

Have you checked this? is this what we want?

2023-12-11 09:15 UTC, irmakyz commented
> > With your solution we are only applying it to 1 sublevel
> 
> Have you checked this? is this what we want?

yes, i fixed it you can see in the commit

2023-12-11 09:17 UTC, irmakyz commented
> Don't we need to pass the slot to the following geo-tree-item?

yes, i passed it after your comments on tuesday

2023-12-11 09:37 UTC, dletran commented on src/elements/GeoTree/GeoTreeItem.vue
> +          <slot name="moreItemResultsTextContent" />
as I mentioned I'd only use results or items but not both, so if we want to tell them apart let's use `moreItemsTextContent`

2023-12-11 09:49 UTC, irmakyz commented on src/elements/GeoTree/GeoTreeItem.vue
> +          <slot name="moreItemResultsTextContent" />
okay then i will use moreItemsTextContent and moreCategoriesTextContent
is it better?

2023-12-11 11:31 UTC, irmakyz commented on src/elements/GeoTree/GeoTreeItem.vue
> +          <slot name="moreItemResultsTextContent" />
- [ ] rename text contents

2023-12-11 11:39 UTC, dletran approved these changes

2023-12-11 11:42 UTC, fofi approved these changes

2023-12-11 11:50 UTC, Navas23 approved these changes

2023-12-13 14:28 UTC, merged