update classnames
geoblink/design-system pull request #144
Opened 2024-01-10 15:21 UTC by irmakyz

2024-01-15 09:40 UTC, Navas23 commented on src/styles/elements/GeoCalendar/_geo-calendar.scss
> -  .geo-calendar__input {
Did we remove these styles?

2024-01-15 16:40 UTC, Navas23 requested changes

2024-01-15 16:40 UTC, Navas23 commented on CHANGELOG.md
> +- `geo-feedback-box__content__icon`: `geo-feedback-box__content__icon`
Review these classes, they are not correct

2024-01-15 16:40 UTC, Navas23 commented on CHANGELOG.md
> +- `geo-segmented-control-item--info--active`: `geo-segmented-control-item--info active`
This is not what we want, right? having an "active" separated class does not make sense

2024-01-16 12:13 UTC, Navas23 commented on src/elements/GeoSegmentedControl/GeoSegmentedControlItem.vue
> +      [`geo-segmented-control-item${outlineSuffix(true)}`]: true,
If we have the suffix here... why do we need it on the rest?

2024-01-16 15:48 UTC, Navas23 approved these changes

2024-01-17 09:17 UTC, dletran approved these changes

2024-01-18 10:46 UTC, merged