add a max-height and overflow for the multiselects
geoblink/design-system pull request #146
Opened 2024-01-22 16:53 UTC by irmakyz

2024-01-23 08:55 UTC, Navas23 requested changes
We are missing the changelog update

2024-01-23 08:55 UTC, Navas23 commented on src/styles/elements/GeoSelect/_geo-multi-select.scss
> +    max-height: 128px;
Have we agreed these changes with product?

2024-01-23 09:12 UTC, irmakyz commented on src/styles/elements/GeoSelect/_geo-multi-select.scss
> +    max-height: 128px;
- [ ] confirm with product

2024-01-23 09:22 UTC, irmakyz commented on src/styles/elements/GeoSelect/_geo-multi-select.scss
> +    max-height: 128px;
i have just confirmed

2024-01-23 09:56 UTC, dletran approved these changes

2024-01-23 09:57 UTC, Navas23 requested changes

2024-01-23 09:57 UTC, Navas23 commented on src/styles/elements/GeoSelect/_geo-multi-select.scss
> +    max-height: 128px;
Perfect, add the changes to the changelog then

2024-01-23 09:57 UTC, dletran reviewed
Let's not forget about adding an entry to the changelog

2024-01-23 10:20 UTC, irmakyz commented
> Let's not forget about adding an entry to the changelog

- [ ] add changelog

2024-01-25 11:07 UTC, Navas23 approved these changes

2024-01-25 11:33 UTC, fofi approved these changes

2024-01-26 14:23 UTC, merged