Feature/core 8692 select toggle button
geoblink/design-system pull request #89
Opened 2021-04-09 14:56 UTC by dletran

2021-04-09 15:06 UTC, fofi approved these changes

2021-04-12 07:34 UTC, Navas23 requested changes
Only one small comment, good job!

2021-04-12 07:34 UTC, Navas23 commented on test/unit/specs/elements/GeoDropdown/GeoDropdownRegularButton.spec.js
> +  it('Should apply proper class when icon position left', function () {
This should be icon position right

2021-04-12 07:40 UTC, dletran commented on test/unit/specs/elements/GeoDropdown/GeoDropdownRegularButton.spec.js
> +  it('Should apply proper class when icon position left', function () {
ah true! let me change it

2021-04-12 07:41 UTC, Navas23 approved these changes

2021-04-13 08:11 UTC, merged