Feature/core 9155 fix latest date year
geoblink/design-system pull request #98
Opened 2021-09-22 07:22 UTC by dletran

2021-09-22 08:33 UTC, fofi approved these changes
Can this happen with other granularity?

2021-09-22 08:37 UTC, dletran commented
> Can this happen with other granularity?

@fofi I'll check it for month too, which probably it's the same, and I'll apply the same solution in that case

2021-09-22 08:54 UTC, Navas23 approved these changes

2021-09-22 08:57 UTC, fofi requested changes
I think we should add some tests for this cases

2021-09-22 08:57 UTC, fofi commented on src/elements/GeoCalendar/GeoCalendar.vue
> +      this.fromRawDate = validatedRange.start
Why changing this code?

2021-09-22 08:57 UTC, fofi commented on src/elements/GeoCalendar/GeoCalendar.vue
> +      const unverifiedRange = this.getUnverifiedRange(firstDayOfMonth, possibleLastDayOfSelectedMonth, isSettingFromDate)
Should we do the same with the initial day?

2021-09-22 09:00 UTC, dletran commented on src/elements/GeoCalendar/GeoCalendar.vue
> +      const unverifiedRange = this.getUnverifiedRange(firstDayOfMonth, possibleLastDayOfSelectedMonth, isSettingFromDate)
if the initial day is before the latest date we won't allow to select it in the picker itself

2021-09-22 09:02 UTC, dletran commented on src/elements/GeoCalendar/GeoCalendar.vue
> +      this.fromRawDate = validatedRange.start
If we apply the endOfQuarter after the validatedRange we'd use the end of the quarter even if it's after the latest date

2021-09-22 09:28 UTC, fofi commented on src/elements/GeoCalendar/GeoCalendar.vue
> +      const unverifiedRange = this.getUnverifiedRange(firstDayOfMonth, possibleLastDayOfSelectedMonth, isSettingFromDate)
I mean if the firstDayOfMonth is smaller than earliestDate ?

2021-09-22 09:59 UTC, dletran commented on src/elements/GeoCalendar/GeoCalendar.vue
> +      const unverifiedRange = this.getUnverifiedRange(firstDayOfMonth, possibleLastDayOfSelectedMonth, isSettingFromDate)
ah good point! I'll have a look

2021-09-22 13:56 UTC, fofi reviewed
What about selectWeek ?

2021-09-23 08:01 UTC, dletran commented
> What about selectWeek ?

@fofi we don't allow selecting a "non-complete" week on the picker, although we could add the verification just in case we change that in the future so everything works the same way, wdyt?

2021-09-23 08:20 UTC, fofi approved these changes

2021-09-23 08:21 UTC, fofi commented
> > What about selectWeek ?
> 
> @fofi we don't allow selecting a "non-complete" week on the picker, although we could add the verification just in case we change that in the future so everything works the same way, wdyt?

Whatever you think is best, on my side is enough

2021-09-23 08:51 UTC, fofi approved these changes

2021-09-23 15:49 UTC, merged